### ISSUE TITLE
updates for COSIM.md

### ISSUE THREAD

**Issue by cylinbao** [bespoke-silicon-group/bsg_bladerunner#28]
To make this instructions more up-to-date and easy to follow.
I think it will need to mention 
- SSH key for using the makefile setup
- add python test for the testbenches

**Comment by drichmond** [comment]
Hi Chien-Yu, 

Thanks for the feedback!

What do you mean by “Add python test for the testbenches?”

Dustin

**Comment by cylinbao** [comment]
sorry, I'm unclear.
So in below section, it just mentions three subsuites, but actually it's four now.
### Running a Single Regression Subsuite

At the moment the regression subsuites are:

1. library
2. spmd
3. cuda

**Comment by drichmond** [comment]
Aha, yes. Well, this documentation is out of date, because it’s 24 hours behind bsg_f1...
