### ISSUE TITLE
Make `make setup` check shell before executing

### ISSUE THREAD

**Issue by save-buffer** [bespoke-silicon-group/bsg_bladerunner#41]
Amazon's setup_hdk.sh doesn't work if it's not from bash. We should either ensure we run it from bash in the Makefile or just don't execute and exit with an error if we call make setup from not bash.

**Comment by drichmond** [comment]
What would happen if we switched to bash while executing this line: 

`https://github.com/bespoke-silicon-group/bsg_bladerunner/blob/1343728531d8e788ab63eb64457faced67bbcf7a/amibuild.mk#L66`

**Comment by save-buffer** [comment]
That seems to work. Updated PR.

**Comment by save-buffer** [comment]
Addressed in #40

**Comment by drichmond** [comment]
Resolved in #40

**Comment by drichmond** [comment]
Damn, race condition :p

**Comment by save-buffer** [comment]
LOL nice
