### ISSUE TITLE
Older version of Git repo

### ISSUE THREAD

**Issue by amithmath** [bespoke-silicon-group/bsg_bladerunner#58]
I would like to download V3.5.2. When I  downloaded repo at this link: https://github.com/bespoke-silicon-group/bsg_bladerunner/releases/tag/v3.5.2 other directories such as bsg_f1, bsg_manycore, basejump_stl, etc. are all empty. May I ask where to get these repo? I checked at: https://github.com/bespoke-silicon-group/bsg_replicant  and other dependencies to see if there are older versions, unfortunately, there are no older versions.

**Comment by mrutt92** [comment]
Please checkout the README as it gives you instructions on initializing this repo which includes retrieving the source of the child repositories.
